server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVCE
          uri: lb://USER-SERVICE
          predicates:
            - Path: /users/**

        - id: RATING-SERVCE
          uri: lb://RATING-SERVICE
          predicates:
            - Path: /ratings/**

        - id: HOTEL-SERVCE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path: /hotels/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
